### PR TITLE
Update packages for Code Editor

### PR DESCRIPTION
**Pull request by vitPinchuk**
Await: [PR](https://github.com/VolkovLabs/business-packages/pull/75)
Resolves: #568

### CODE REVIEW

**Review by asimonok — APPROVED** [review]
Looks good!

@mikhail-vl ready for review

**Comment by vitPinchuk** [comment]
@asimonok @mikhail-vl ready for review

**Review by asimonok — APPROVED** [review]
Looks good!

@mikhail-vl ready for review

**Review by mikhail-vl — APPROVED** [review]
Looks good!

**Pull request merged**
